
 
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
 
import { Geist, Geist_Mono } from "next/font/google";

import "../styles/globals.scss";
import Header from "../components/header/Header";
import Footer from "../components/footer/Footer";
import { SessionProvider } from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Archivo+Black&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
          rel="stylesheet"
        />
        
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <SessionProvider>{children}</SessionProvider>
        
        <Footer />
      </body>
    </html>
  );
}
